"""AGV 升降高度控制基础公共接口。"""

from .can_pump import (
    CanLinkError,
    CanLinkInfo,
    CanPump,
    CanPumpError,
    encode_nmt_start,
    encode_pump_command,
    inspect_can_link,
    parse_pump_feedback,
    select_safe_command,
)
from .calibration import (
    LIFT_PWM_LEVELS,
    LOWER_VALVE_LEVELS,
    CalibrationBundle,
    CalibrationError,
    CalibrationStore,
    LiftCalibrationResult,
    LiftCalibrationSession,
    LiftTrial,
    LowerCalibrationResult,
    LowerCalibrationSession,
    LowerTrial,
    UpperLimitSurvey,
    analyze_lift_trials,
    analyze_lower_trials,
)
from .config import AppConfig, CanConfig, ConfigError, ControlConfig, SensorConfig, load_config
from .controller import ControllerState, HeightController
from .modbus_rtu import ModbusRtuHeightSource
from .simulation import HydraulicLiftSimulator, HydraulicSnapshot
from .types import HeightSample, HeightSource, PumpCommand, PumpFeedback

__all__ = [
    "AppConfig",
    "CanLinkError",
    "CanLinkInfo",
    "CanConfig",
    "CanPump",
    "CanPumpError",
    "CalibrationBundle",
    "CalibrationError",
    "CalibrationStore",
    "ConfigError",
    "ControlConfig",
    "ControllerState",
    "HeightSample",
    "HeightController",
    "HeightSource",
    "HydraulicLiftSimulator",
    "HydraulicSnapshot",
    "ModbusRtuHeightSource",
    "LIFT_PWM_LEVELS",
    "LOWER_VALVE_LEVELS",
    "LiftCalibrationResult",
    "LiftCalibrationSession",
    "LiftTrial",
    "LowerCalibrationResult",
    "LowerCalibrationSession",
    "LowerTrial",
    "UpperLimitSurvey",
    "PumpCommand",
    "PumpFeedback",
    "SensorConfig",
    "encode_nmt_start",
    "encode_pump_command",
    "inspect_can_link",
    "load_config",
    "parse_pump_feedback",
    "select_safe_command",
    "analyze_lift_trials",
    "analyze_lower_trials",
]
